ERROR - 2023-01-13 00:00:30 --> Error connecting to the database: mysqli_sql_exception: No connection could be made because the target machine actively refused it in C:\xampp\htdocs\atala\system\Database\MySQLi\Connection.php:171
Stack trace:
#0 C:\xampp\htdocs\atala\system\Database\MySQLi\Connection.php(171): mysqli->real_connect('localhost', 'root', '', 'supplier materi...', 3306, '', 0)
#1 C:\xampp\htdocs\atala\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\atala\system\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\atala\app\Controllers\Root.php(100): CodeIgniter\Database\BaseConnection->query('select * from p...')
#4 C:\xampp\htdocs\atala\system\CodeIgniter.php(927): App\Controllers\Root->proseslogin()
#5 C:\xampp\htdocs\atala\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Root))
#6 C:\xampp\htdocs\atala\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\atala\public\index.php(67): CodeIgniter\CodeIgniter->run()
#8 C:\xampp\htdocs\atala\system\Commands\Server\rewrite.php(46): require_once('C:\\xampp\\htdocs...')
#9 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No connection could be made because the target machine actively refused it in C:\xampp\htdocs\atala\system\Database\MySQLi\Connection.php:215
Stack trace:
#0 C:\xampp\htdocs\atala\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\atala\system\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\atala\app\Controllers\Root.php(100): CodeIgniter\Database\BaseConnection->query('select * from p...')
#3 C:\xampp\htdocs\atala\system\CodeIgniter.php(927): App\Controllers\Root->proseslogin()
#4 C:\xampp\htdocs\atala\system\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Root))
#5 C:\xampp\htdocs\atala\system\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\atala\public\index.php(67): CodeIgniter\CodeIgniter->run()
#7 C:\xampp\htdocs\atala\system\Commands\Server\rewrite.php(46): require_once('C:\\xampp\\htdocs...')
#8 {main}
CRITICAL - 2023-01-13 00:00:30 --> Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it
in SYSTEMPATH\Database\BaseConnection.php on line 418.
 1 SYSTEMPATH\Database\BaseConnection.php(561): CodeIgniter\Database\BaseConnection->initialize()
 2 APPPATH\Controllers\Root.php(100): CodeIgniter\Database\BaseConnection->query('select * from pengguna where username = \'admin\' and password = \'21232f297a57a5a743894a0e4a801fc3\'')
 3 SYSTEMPATH\CodeIgniter.php(927): App\Controllers\Root->proseslogin()
 4 SYSTEMPATH\CodeIgniter.php(482): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Root))
 5 SYSTEMPATH\CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 7 SYSTEMPATH\Commands\Server\rewrite.php(46): require_once('FCPATH\\index.php')
